-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "startYear" SET DATA TYPE TEXT,
ALTER COLUMN "endYear" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
