//Importing  CSS File
import './globals.css';
import 'react-quill/dist/quill.snow.css'

//Importing Components
import Header from '../components/Header';

export const metadata = {
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
