//Importing  CSS File
import './globals.css';
import 'react-quill/dist/quill.snow.css'

//Importing Components
import Header from '../components/Header';
import Loader from '../components/Loader';
import Toast from '../components/Toast';

//Importing Context
import AlertContextProvider from '../contextproviders/AlertContextProvider';
import LoadingContextProvider from '../contextproviders/LoadingContextProvider';

export const metadata = {
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LoadingContextProvider>
          <AlertContextProvider>
            <Header />
            <Loader />
            {children}
            <Toast />
          </AlertContextProvider>
        </LoadingContextProvider>
      </body>
    </html>
  );
}
