//Importing  CSS File
import './globals.css';
import 'react-quill/dist/quill.snow.css'

//Importing Components
import Header from '../components/Header';
import Loader from '../components/Loader';
import Toast from '../components/Toast';

//Importing Context
import AlertContext from '../context/AlertContext';
import LoadingContext from '../context/LoadingContext';

export const metadata = {
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AlertContext>
          <LoadingContext>
            <Header />
            <Loader />
            {children}
            <Toast />
          </LoadingContext>
        </AlertContext>
      </body>
    </html>
  );
}
